[package]
name = "neoprl"
version = "0.1.0"
authors = ["Alan Hu <alanh@ccs.neu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
abt = { path = "abt-rs", version = "0.1.0" }
